// CPU-only inventory helper. Output contains identities and offsets, never game bytes.
#include "gpu/shader/resource_scan.h"
#include <chrono>
#include <iomanip>
#include <iostream>

using namespace xenos::resources;
#ifdef _WIN32
int wmain(int argc, wchar_t** argv) {
#else
int main(int argc, char** argv) {
#endif
    try {
        if (argc<3) throw std::runtime_error("usage: generate_cpx_shader_index <game or disc directory> <new metadata file> [additional game roots...]");
        const fs::path root=argv[1], output=argv[2];
        if (fs::exists(output)) throw std::runtime_error("output already exists; choose a new path");
        std::vector<fs::path> roots;
        auto addRoot=[&](const fs::path& candidate) {
            const auto before=roots.size();
            if (fs::is_regular_file(candidate/"LO.fpi")) roots.push_back(candidate);
            else for (int i=1;i<=4;++i) {
                const auto disc=candidate/("disc"+std::to_string(i));
                if (fs::is_regular_file(disc/"LO.fpi")) roots.push_back(disc);
            }
            if (roots.size()==before) throw std::runtime_error("no LO.fpi in supplied game root");
        };
        addRoot(root);
        for (int i=3;i<argc;++i) addRoot(fs::path(argv[i]));
        if (roots.empty()) throw std::runtime_error("no LO.fpi resources found");
        struct Package { uint32_t stored,decoded; std::vector<IndexEntry> entries; };
        std::map<std::string,Package> profiles;
        struct Binding { ResourceExtent extent; std::string digest; };
        struct Archive { std::string fpi,name; uint64_t size; std::vector<Binding> bindings; };
        std::vector<Archive> archives;
        std::vector<uint8_t> encoded,decoded;
        uint64_t bytesRead=0,decodedBytes=0,packages=0,extents=0;
        const auto started=std::chrono::steady_clock::now();
        for (const auto& dir:roots) {
          const auto fpiDigest=FpiDigest(dir/"LO.fpi",bytesRead);
          for (const auto& [file,records]:ReadResourceExtents(dir/"LO.fpi",&bytesRead)) {
            archives.push_back({fpiDigest,file.filename().string(),fs::file_size(file),{}});
            auto& bindings=archives.back().bindings;
            std::ifstream in(file,std::ios::binary);
            for (const auto& record:records) {
                ++extents;
                bindings.push_back({record,{}});
                if (record.size<16) continue;
                uint8_t header[16]; in.clear(); in.seekg(record.offset);
                if (!in.read(reinterpret_cast<char*>(header),16)) throw std::runtime_error("short extent header read");
                bytesRead+=16;
                if (header[0]!='c' || header[1]!='p' || header[2]!='x') continue;
                ++packages;
                cpx::Header framing;
                if (!cpx::ReadHeader(header,framing) || framing.storedSize!=record.size) throw std::runtime_error("invalid CPX size");
                encoded.resize(record.size); std::copy(std::begin(header),std::end(header),encoded.begin());
                if (!in.read(reinterpret_cast<char*>(encoded.data()+16),encoded.size()-16)) throw std::runtime_error("short package read");
                bytesRead+=encoded.size()-16;
                const auto digest=Sha256Hex(Sha256(encoded));
                bindings.back().digest=digest;
                if (profiles.contains(digest)) continue;
                if (!cpx::Decode(encoded,decoded)) throw std::runtime_error("invalid CPX decoder input");
                decodedBytes+=decoded.size();
                profiles.emplace(digest,Package{record.size,uint32_t(decoded.size()),ContainerLocations(decoded)});
            }
            std::cout << file.parent_path().filename().string() << '/' << file.filename().string()
                      << " packages=" << packages << " unique=" << profiles.size() << std::endl;
        }
        }
        if (profiles.empty()) throw std::runtime_error("no CPX packages; refusing empty inventory");
        if (!output.parent_path().empty()) fs::create_directories(output.parent_path());
        auto temporary=output; temporary+=".tmp";
        std::ofstream out(temporary,std::ios::binary|std::ios::trunc);
        out << "// Generated by tools/generate_cpx_shader_index.py. Metadata only; no game bytes.\n"
               "#pragma once\n#include \"resource_index_types.h\"\nnamespace xenos::resources::builtin {\n";
        size_t id=0,locations=0,empty=0;
        for (const auto& [digest,profile]:profiles) {
            if (profile.entries.empty()) { ++id; ++empty; continue; }
            out << "inline constexpr IndexEntry cpx_entries_" << id++ << "[] = {\n";
            for (const auto& entry:profile.entries) out << "    {" << entry.offset << "ULL," << entry.size << ",0x"
                << std::hex << entry.hash << std::dec << "ULL," << (entry.pixel?"true":"false") << "},\n";
            out << "};\n"; locations+=profile.entries.size();
        }
        out << "inline const CpxIndexPackage cpxPackages[] = {\n"; id=0;
        for (const auto& [digest,profile]:profiles) {
            out << "    {\"" << digest << "\"," << profile.stored << ',' << profile.decoded << ',';
            if (profile.entries.empty()) out << "{}";
            else out << "cpx_entries_" << id;
            out << "},\n"; ++id;
        }
        out << "};\n";
        std::map<std::string,size_t> profileIds; id=0;
        for (const auto& [digest,profile]:profiles) profileIds.emplace(digest,id++);
        for (size_t i=0;i<archives.size();++i) {
            if (archives[i].bindings.empty()) continue;
            out << "inline constexpr CpxIndexExtent cpx_extents_" << i << "[] = {\n";
            for (const auto& binding:archives[i].bindings) {
                out << "    {" << binding.extent.offset << "ULL," << binding.extent.size << ',';
                if (binding.digest.empty()) out << "UINT32_MAX";
                else out << profileIds.at(binding.digest);
                out << "},\n";
            }
            out << "};\n";
        }
        out << "inline const CpxIndexArchive cpxArchives[] = {\n";
        for (size_t i=0;i<archives.size();++i) {
            const auto& archive=archives[i];
            out << "    {\"" << archive.fpi << "\",\"" << archive.name << "\"," << archive.size << "ULL,";
            if (archive.bindings.empty()) out << "{}"; else out << "cpx_extents_" << i;
            out << "},\n";
        }
        out << "};\n}\n"; out.close();
        if (!out) throw std::runtime_error("cannot write metadata");
        fs::rename(temporary,output);
        std::cout << "packages=" << packages << " unique=" << profiles.size() << " empty=" << empty
                  << " locations=" << locations << " extents=" << extents << " bytes_read=" << bytesRead
                  << " decoded_bytes=" << decodedBytes << " ms="
                  << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-started).count() << '\n';
    } catch (const std::exception& e) { std::cerr << e.what() << '\n'; return 1; }
}
